// Employee Account 

export const EMPLOYEE_LOGIN_AUTH = "EMPLOYEE_LOGIN_AUTH";
export const GET_EMPLOYEE_LOGIN_AUTH = "GET_EMPLOYEE_LOGIN_AUTH";
export const EMPLOYEE_LOGOUT = "EMPLOYEE_LOGOUT";

// Masters

export const GET_WORKSPACES_LIST = "GET_WORKSPACES_LIST";
export const GET_PROJECTS_LIST = "GET_PROJECTS_LIST";
export const GET_TASKS_LIST = "GET_TASKS_LIST";

// Employee Activities
export const GET_ACTIVITIES_LIST = "GET_ACTIVITIES_LIST";
